### ISSUE TITLE
Question on Scope

### ISSUE THREAD

**Issue by jnews0n** [dm-academy/aitm#1]
Hi Charles,

This looks like an interesting project, with timely and relevant topics.
I'm interested to know why security has been omitted from the scope of the text.

Regards,
Jon

**Comment by CharlesTBetz** [comment]
Hi Jon

I admit this is a gap, but am inclined to handle it throughout each section as an aspect, with primary attention in Chapter 10 under Governance. I am not entirely happy with this approach, but need to keep chapter count to 12. Ideas?

Charlie

ps sorry for delay, need to make sure these are flagged better in my email.

**Comment by CharlesTBetz** [comment]
re: why, security is a personal gap of mine. I'm always transparent about this. Can only cover so much ground in one's life!

**Comment by jnews0n** [comment]
Hi Charlie

With the chapter count being a constraint, threading security in a braided manner throughout the text may certainly be the apt strategy.

Am certainly happy and willing to contribute where I can.

Cheers, 
Jon
