### ISSUE TITLE
Different photos?

### ISSUE THREAD

**Issue by fralippolippi** [dm-academy/aitm#3]
I would think some photos showing a bit more diversity would be a positive thing. 

I have spent some time looking for free photos (open for commercial use) and did find it surprisingly difficult to find photos of non white people using computers. I have not explored too far into the paid realm - if this continues to be an issue though I would be open to contributing funds for better stock photos to be used with this effort.

**Comment by CharlesTBetz** [comment]
Yes, I spent some time looking as well - not easy.

**Comment by CharlesTBetz** [comment]
Added more diversity e.g.  https://github.com/dm-academy/aitm/blob/master/images/1.01a-woman.jpg https://github.com/dm-academy/aitm/blob/master/images/1.01b-woman.jpg - will continue to work to this
